apiVersion: v1
kind: Namespace
metadata: { name: bookstore }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: default-deny-all, namespace: bookstore }
spec:
  podSelector: {}
  policyTypes: ["Ingress","Egress"]
