# k8s/30-services-internal-nlb.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: bookstore
  labels: { app: catalog }
spec:
  type: NodePort
  selector: { app: catalog-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31080
    appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: bookstore
  labels: { app: cart }
spec:
  type: NodePort
  selector: { app: cart-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31081
    appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: bookstore
  labels: { app: order }
spec:
  type: NodePort
  selector: { app: order-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31082
    appProtocol: http
